### PR TITLE
Add More Entries

### PR DESCRIPTION
**Pull request by FlorianWendelborn**
- absolute -> relative
- active -> passive
- addEventListener -> removeEventListener
- argc -> argv
- cipher -> decipher
- connected -> disconnected
- decrypted -> encrypted
- horizontal -> vertical
- impossible -> possible
- inner -> outer
- invalid -> valid

### CODE REVIEW

**Comment by FlorianWendelborn** [comment]
Oh, BTW we should really find a better solution for all of this. Some kind of metadata CSON/JSON file and a README generator would be neat.

**Comment by severinkaderli** [comment]
I'm gonna merge this and I will find a solution for generating the README file. That should be easily doable with a gulp task or so.

**Comment by FlorianWendelborn** [comment]
@severinkaderli Thanks, appreciated. If you look for a solution, I'd suggest that we also move the data out of the code, probably into a nested JSON/CSON (keys are current categories, keys of keys are current entries).

**Comment by FlorianWendelborn** [comment]
@severinkaderli Can you also publish this relatively soon? I'm using `atom-reverser` quite a lot and would appreciate to be able to upgrade.

**Comment by severinkaderli** [comment]
@dodekeract I just published the new version. The keywords are now defined in keywords.json inside the lib folder. There's also a gulp readme task that updates the README file with the current keywords.

**Pull request merged**
